using Sirenix.OdinInspector;
using Sirenix.Serialization;
using UnityEngine;

[CreateAssetMenu(fileName = "Unity services - Environment - Name", menuName = "ScriptableObjects/Unity Services/New Environment")]
public class UnityServicesEnvironment : SerializedScriptableObject
{
    [OdinSerialize] public string EnvironmentName { get; private set; }
    [OdinSerialize, InfoBox("This token have been generated by Unity Services Dashboard, and should be matching")] public string EnvironmentId { get; set; }
}
